name: Build Rive framework

on:
  push
  # push:
  #   tags:
  #     - '*'

jobs:
  build_frameworks:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.RIVE_REPO_PAT }}
          submodules: recursive
      - name: Init submodule
        run: git submodule update --init
      - id: build_iphoneos
        name: Build release iphoneos framework
        run: sh ./scripts/buildFramework.sh  -t iphoneos -c Release
      - id: build_iphonesimulator
        name: Build release iphonesimulator framework
        run: sh ./scripts/buildFramework.sh  -t iphonesimulator -c Release
      - id: merge_frameworks
        if: steps.build_iphoneos.conclusion == 'success' && steps.build_iphonesimulator.conclusion == 'success'
        name: Merge created frameworks
        run: sh ./scripts/mergeFrameworks.sh -c Release
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: rive-framework
          path: build/RiveRuntime.xcframework
