name: Build Rive framework

on:
  push
  # push:
  #   tags:
  #     - '*'

jobs:
  # build_frameworks:
  #   name: Create RiveRuntime.xcframework
  #   runs-on: macos-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #       with:
  #         token: ${{ secrets.RIVE_REPO_PAT }}
  #         submodules: recursive
  #     - name: Init submodule
  #       run: git submodule update --init
  #     - id: build_iphoneos
  #       name: Build release iphoneos framework
  #       run: sh ./scripts/buildFramework.sh  -t iphoneos -c Release
  #     - id: build_iphonesimulator
  #       name: Build release iphonesimulator framework
  #       run: sh ./scripts/buildFramework.sh  -t iphonesimulator -c Release
  #     - id: merge_frameworks
  #       if: steps.build_iphoneos.conclusion == 'success' && steps.build_iphonesimulator.conclusion == 'success'
  #       name: Merge created frameworks
  #       run: sh ./scripts/mergeFrameworks.sh -c Release
  #     - name: Upload artifact
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: rive-framework
  #         path: build/RiveRuntime.xcframework

# push framewrok and update podspec
  create_podspec_file:
    name: Create RiveRuntime.podspec
    runs-on: macos-latest
    # needs: build_frameworks
    steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
            token: ${{ secrets.RIVE_REPO_PAT }}
            submodules: recursive
        - name: Get tag
          id: tag
          run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
        - name: Check tag
          env:
            RELEASE_VERSION: ${{ steps.tag.outputs.tag }}
          run: |
            echo $RELEASE_VERSION
            echo ${{ steps.tag.outputs.tag }}
        - name: Read podspec.txt file
          uses: pCYSl5EDgo/cat@master
          id: podspec
          with:
            path: .github/workflows/podspec.txt
        - name: Create *.podspec
          run: |
            cat > RiveRuntime.podspec <<-EOF                      
            ${{ steps.podspec.outputs.text }}
            EOF
          env:
            GITHUB_AUTHOR: ${{ github.actor }}
        # just to test it...
        - name: Upload artifact
          uses: actions/upload-artifact@v2
          with:
            name: rive-podspec
            path: RiveRuntime.podspec

