name: Deploy

on:
  push
  # push:
  #   tags:
  #     - '*'

jobs:
  checkout: 
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.RIVE_REPO_PAT }}
          submodules: recursive
      - name: Init submodule
        run: git submodule update --init

  build_frameworks:
    runs-on: macos-latest
    needs: checkout
    outputs:
      status: ${{ steps.*.conclusion }}
    steps:
      - id: iphoneos
        name: Build release iphoneos framework
        run: sh ./scripts/buildFramework.sh  -t iphoneos -c Release
      - id: iphonesimulator
        name: Build release iphonesimulator framework
        run: sh ./scripts/buildFramework.sh  -t iphonesimulator -c Release

  merge_frameworks:
    runs-on: macos-latest
    needs: build_frameworks
    # if: !contains(needs.build_frameworks.outputs.status, 'failure')
    steps:
      - name: Print status
        run: echo ${{ needs.build_frameworks.outputs.status }}
      - name: Merge created frameworks
        run: sh ./scripts/mergeFrameworks.sh -c Release