name: Deploy

on:
  push
  # push:
  #   tags:
  #     - '*'

jobs:
  create_framework:
    name: Create Rive *.xcframework
    runs-on: macos-latest
    defaults:
      run:
        shell: bash
        working-directory: scripts
    steps:
      - name: build_iphoneos
        run: |
          ls -alt
          ./scripts/buildFramework.sh -t iphoneos -c Release

      - name: Build release iphonesimulator framework
        run: ./scripts/buildFramework.sh -t iphonesimulator -c Release
  
      - name: Merge created frameworks
        run: ./scripts/mergeFrameworks.sh -c Release