name: Deploy

on:
  push
  # push:
  #   tags:
  #     - '*'

jobs:
  checkout: 
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Init submodule
        run: git submodule update --init

  build_frameworks:
    outputs:
      status: ${{ steps.*.conclusion }}
    steps:
      - id: iphoneos
        name: Build release iphoneos framework
        run: sh ./scripts/buildFramework.sh  -t iphoneos -c Release
      - id: iphonesimulator
        name: Build release iphonesimulator framework
        run: sh ./scripts/buildFramework.sh  -t iphonesimulator -c Release

  build_framework_iphonesimulator:
    needs: build_frameworks
    if: !contains(needs.build_frameworks.outputs.status, 'failure')
    steps:
        name: Merge created frameworks
        run: sh ./scripts/buildFramework.sh  -t iphonesimulator -c Release
